package b4j.example;


import anywheresoftware.b4a.BA;

public class pdf extends Object{
public static pdf mostCurrent = new pdf();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.pdf", null);
		ba.loadHtSubs(pdf.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.pdf", ba);
		}
	}
    public static Class<?> getObject() {
		return pdf.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static anywheresoftware.b4j.objects.JFX _fx = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static String  _basic() throws Exception{
b4j.example.pdfmaker _maker = null;
 //BA.debugLineNum = 6;BA.debugLine="Sub basic";
 //BA.debugLineNum = 7;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 8;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 9;BA.debugLine="maker.AddString(\"First paragraph\")";
_maker._addstring /*b4j.example.pdfmaker*/ ("First paragraph");
 //BA.debugLineNum = 10;BA.debugLine="maker.AddString(\"Another paragraph, this time a l";
_maker._addstring /*b4j.example.pdfmaker*/ ("Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines");
 //BA.debugLineNum = 11;BA.debugLine="maker.Open";
_maker._open /*String*/ ();
 //BA.debugLineNum = 12;BA.debugLine="End Sub";
return "";
}
public static String  _columns() throws Exception{
b4j.example.pdfmaker _maker = null;
b4j.example.pdfcolumns _cols = null;
b4j.example.pdfcolumns _cols3 = null;
b4j.example.pdfcolumns _cols4 = null;
b4j.example.pdfcolumns _cols5 = null;
b4j.example.pdfcolumns _cols6 = null;
b4j.example.pdftext _txt = null;
b4j.example.pdfcolumns _col7 = null;
b4j.example.pdfstyle _style1 = null;
b4j.example.pdfstyle _style2 = null;
b4j.example.pdfcolumns _colx = null;
 //BA.debugLineNum = 159;BA.debugLine="Sub columns";
 //BA.debugLineNum = 160;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 161;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 162;BA.debugLine="maker.defaultStyle.columnGap = 20";
_maker._defaultstyle /*b4j.example.pdfstyle*/ ._columngap /*int*/  = (int) (20);
 //BA.debugLineNum = 164;BA.debugLine="maker.AddString(\"Here we have 2 equal sized colum";
_maker._addstring /*b4j.example.pdfmaker*/ ("Here we have 2 equal sized columns...");
 //BA.debugLineNum = 166;BA.debugLine="Dim cols As PDFColumns = maker.CreateColumns";
_cols = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 167;BA.debugLine="cols.style.alignmentjustify = True";
_cols._style /*b4j.example.pdfstyle*/ ._alignmentjustify /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 168;BA.debugLine="cols.AddText(maker.CreateText(\"Column 1\"))";
_cols._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 1"));
 //BA.debugLineNum = 169;BA.debugLine="cols.AddText(maker.CreateText(\"Column 2\"))";
_cols._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2"));
 //BA.debugLineNum = 170;BA.debugLine="maker.AddColumns(cols)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols);
 //BA.debugLineNum = 173;BA.debugLine="maker.AddString(\"Here we have 3 equal sized colum";
_maker._addstring /*b4j.example.pdfmaker*/ ("Here we have 3 equal sized columns...");
 //BA.debugLineNum = 174;BA.debugLine="Dim cols3 As PDFColumns = maker.CreateColumns";
_cols3 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 175;BA.debugLine="cols3.AddText(maker.CreateText(\"Column 1\"))";
_cols3._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 1"));
 //BA.debugLineNum = 176;BA.debugLine="cols3.AddText(maker.CreateText(\"Column 2\"))";
_cols3._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2"));
 //BA.debugLineNum = 177;BA.debugLine="cols3.AddText(maker.CreateText(\"Column 3\"))";
_cols3._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 3"));
 //BA.debugLineNum = 178;BA.debugLine="maker.AddColumns(cols3)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols3);
 //BA.debugLineNum = 181;BA.debugLine="maker.AddString(\"Here we specify widths for each";
_maker._addstring /*b4j.example.pdfmaker*/ ("Here we specify widths for each column...");
 //BA.debugLineNum = 182;BA.debugLine="Dim cols4 As PDFColumns = maker.CreateColumns";
_cols4 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 183;BA.debugLine="cols4.AddText(maker.CreateText(\"Column 1\").SetWid";
_cols4._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 1")._setwidth /*b4j.example.pdftext*/ (BA.NumberToString(90)));
 //BA.debugLineNum = 184;BA.debugLine="cols4.AddText(maker.CreateText(\"Column 2\").SetWid";
_cols4._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 185;BA.debugLine="cols4.AddText(maker.CreateText(\"Column 3\").SetWid";
_cols4._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 3")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 186;BA.debugLine="cols4.AddText(maker.CreateText(\"Column 4\").SetWid";
_cols4._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 4")._setwidth /*b4j.example.pdftext*/ (BA.NumberToString(90)));
 //BA.debugLineNum = 187;BA.debugLine="maker.AddColumns(cols4)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols4);
 //BA.debugLineNum = 189;BA.debugLine="maker.AddString(\"Auto columns set their width dep";
_maker._addstring /*b4j.example.pdfmaker*/ ("Auto columns set their width depending on their content...");
 //BA.debugLineNum = 190;BA.debugLine="Dim cols5 As PDFColumns = maker.CreateColumns";
_cols5 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 191;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 1\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 1")._setwidth /*b4j.example.pdftext*/ ("auto"));
 //BA.debugLineNum = 192;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 2\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 193;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 3\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 3")._setwidth /*b4j.example.pdftext*/ (BA.NumberToString(50)));
 //BA.debugLineNum = 194;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 4\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 4")._setwidth /*b4j.example.pdftext*/ ("auto"));
 //BA.debugLineNum = 195;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 5\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 5")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 196;BA.debugLine="maker.AddColumns(cols5)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols5);
 //BA.debugLineNum = 198;BA.debugLine="maker.AddString(\"Nesting columns...\")";
_maker._addstring /*b4j.example.pdfmaker*/ ("Nesting columns...");
 //BA.debugLineNum = 199;BA.debugLine="Dim cols6 As PDFColumns = maker.CreateColumns";
_cols6 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 200;BA.debugLine="Dim txt As PDFText = maker.CreateText(\"This is my";
_txt = _maker._createtext /*b4j.example.pdftext*/ ("This is my text for nested columns...");
 //BA.debugLineNum = 201;BA.debugLine="txt.style.fontSize = 9";
_txt._style /*b4j.example.pdfstyle*/ ._fontsize /*int*/  = (int) (9);
 //BA.debugLineNum = 202;BA.debugLine="txt.style.width = 100";
_txt._style /*b4j.example.pdfstyle*/ ._width /*String*/  = BA.NumberToString(100);
 //BA.debugLineNum = 203;BA.debugLine="cols6.AddText(txt)";
_cols6._addtext /*b4j.example.pdfcolumns*/ (_txt);
 //BA.debugLineNum = 205;BA.debugLine="cols6.AddText(maker.CreateText(\"Column 2\").SetWid";
_cols6._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2")._setwidth /*b4j.example.pdftext*/ ("auto"));
 //BA.debugLineNum = 206;BA.debugLine="cols6.AddText(maker.CreateText(\"Column 3\").SetWid";
_cols6._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 3")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 208;BA.debugLine="Dim col7 As PDFColumns = maker.CreateColumns";
_col7 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 209;BA.debugLine="col7.AddString(\"This is nested!\")";
_col7._addstring /*b4j.example.pdfcolumns*/ ("This is nested!");
 //BA.debugLineNum = 210;BA.debugLine="col7.AddString(\"This is another nested column!\")";
_col7._addstring /*b4j.example.pdfcolumns*/ ("This is another nested column!");
 //BA.debugLineNum = 212;BA.debugLine="cols6.AddColumns(col7)";
_cols6._addcolumns /*b4j.example.pdfcolumns*/ (_col7);
 //BA.debugLineNum = 213;BA.debugLine="maker.AddColumns(cols6)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols6);
 //BA.debugLineNum = 216;BA.debugLine="Dim style1 As PDFStyle = maker.CreateStyle(\"bigge";
_style1 = _maker._createstyle /*b4j.example.pdfstyle*/ ("bigger");
 //BA.debugLineNum = 217;BA.debugLine="style1.fontSize = 18";
_style1._fontsize /*int*/  = (int) (18);
 //BA.debugLineNum = 218;BA.debugLine="style1.bold = True";
_style1._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 219;BA.debugLine="maker.AddStyle(style1)";
_maker._addstyle /*String*/ (_style1);
 //BA.debugLineNum = 221;BA.debugLine="Dim style2 As PDFStyle = maker.CreateStyle(\"heade";
_style2 = _maker._createstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 222;BA.debugLine="style2.fontSize = 15";
_style2._fontsize /*int*/  = (int) (15);
 //BA.debugLineNum = 223;BA.debugLine="style2.italics = True";
_style2._italics /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 224;BA.debugLine="maker.AddStyle(style2)";
_maker._addstyle /*String*/ (_style2);
 //BA.debugLineNum = 226;BA.debugLine="Dim colX As PDFColumns = maker.CreateColumns";
_colx = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 227;BA.debugLine="colX.style.AddStyle(\"bigger\")";
_colx._style /*b4j.example.pdfstyle*/ ._addstyle /*b4j.example.pdfstyle*/ ("bigger");
 //BA.debugLineNum = 228;BA.debugLine="colX.AddString(\"This is some column data that use";
_colx._addstring /*b4j.example.pdfcolumns*/ ("This is some column data that users the 'bigger' style!");
 //BA.debugLineNum = 229;BA.debugLine="colX.AddText(maker.CreateText(\"Some text with 20";
_colx._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Some text with 20 fontsize")._setfontsize /*b4j.example.pdftext*/ ((int) (20)));
 //BA.debugLineNum = 230;BA.debugLine="maker.AddColumns(colX)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_colx);
 //BA.debugLineNum = 232;BA.debugLine="maker.Open";
_maker._open /*String*/ ();
 //BA.debugLineNum = 233;BA.debugLine="End Sub";
return "";
}
public static String  _inlinestyles() throws Exception{
b4j.example.pdfmaker _maker = null;
b4j.example.pdfstyle _s1 = null;
b4j.example.pdfstyle _s2 = null;
b4j.example.pdftext _hdr = null;
b4j.example.pdfparagraphs _para = null;
 //BA.debugLineNum = 118;BA.debugLine="Sub inlineStyles";
 //BA.debugLineNum = 119;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 120;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 122;BA.debugLine="Dim s1 As PDFStyle = maker.CreateStyle(\"header\")";
_s1 = _maker._createstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 123;BA.debugLine="s1.fontSize = 18";
_s1._fontsize /*int*/  = (int) (18);
 //BA.debugLineNum = 124;BA.debugLine="s1.bold = True";
_s1._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 125;BA.debugLine="maker.AddStyle(s1)";
_maker._addstyle /*String*/ (_s1);
 //BA.debugLineNum = 127;BA.debugLine="Dim s2 As PDFStyle = maker.CreateStyle(\"bigger\")";
_s2 = _maker._createstyle /*b4j.example.pdfstyle*/ ("bigger");
 //BA.debugLineNum = 128;BA.debugLine="s2.fontsize = 15";
_s2._fontsize /*int*/  = (int) (15);
 //BA.debugLineNum = 129;BA.debugLine="s2.italics = True";
_s2._italics /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 130;BA.debugLine="maker.AddStyle(s2)";
_maker._addstyle /*String*/ (_s2);
 //BA.debugLineNum = 132;BA.debugLine="Dim hdr As PDFText = maker.CreateText(\"This is a";
_hdr = _maker._createtext /*b4j.example.pdftext*/ ("This is a header")._setstyle /*b4j.example.pdftext*/ ("header");
 //BA.debugLineNum = 133;BA.debugLine="maker.AddText(hdr)";
_maker._addtext /*String*/ (_hdr);
 //BA.debugLineNum = 135;BA.debugLine="Dim para As PDFParagraphs = maker.CreateParagraph";
_para = _maker._createparagraphs /*b4j.example.pdfparagraphs*/ ();
 //BA.debugLineNum = 136;BA.debugLine="para.AddString(\"It is however possible to provide";
_para._addstring /*b4j.example.pdfparagraphs*/ ("It is however possible to provide an array of texts ");
 //BA.debugLineNum = 137;BA.debugLine="para.AddString(\"to the paragraph (instead of a si";
_para._addstring /*b4j.example.pdfparagraphs*/ ("to the paragraph (instead of a single string) and have ");
 //BA.debugLineNum = 138;BA.debugLine="para.AddText(maker.CreateText(\"a better \").SetFon";
_para._addtext /*b4j.example.pdfparagraphs*/ (_maker._createtext /*b4j.example.pdftext*/ ("a better ")._setfontsize /*b4j.example.pdftext*/ ((int) (15))._setbold /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 139;BA.debugLine="para.AddString(\"control over it. \\nEach inline ca";
_para._addstring /*b4j.example.pdfparagraphs*/ ("control over it. \\nEach inline can be ");
 //BA.debugLineNum = 140;BA.debugLine="para.AddText(maker.CreateText(\"styled \").SetFontS";
_para._addtext /*b4j.example.pdfparagraphs*/ (_maker._createtext /*b4j.example.pdftext*/ ("styled ")._setfontsize /*b4j.example.pdftext*/ ((int) (20)));
 //BA.debugLineNum = 141;BA.debugLine="para.AddText(maker.CreateText(\"independently \").S";
_para._addtext /*b4j.example.pdfparagraphs*/ (_maker._createtext /*b4j.example.pdftext*/ ("independently ")._setitalics /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setfontsize /*b4j.example.pdftext*/ ((int) (40)));
 //BA.debugLineNum = 142;BA.debugLine="para.AddString(\"then.\\n\\n\")";
_para._addstring /*b4j.example.pdfparagraphs*/ ("then.\\n\\n");
 //BA.debugLineNum = 143;BA.debugLine="maker.AddParagraphs(para)";
_maker._addparagraphs /*b4j.example.pdfmaker*/ (_para);
 //BA.debugLineNum = 145;BA.debugLine="maker.open";
_maker._open /*String*/ ();
 //BA.debugLineNum = 146;BA.debugLine="End Sub";
return "";
}
public static String  _margins() throws Exception{
b4j.example.pdfmaker _maker = null;
b4j.example.pdfstyle _hdr = null;
b4j.example.pdfstyle _sh = null;
b4j.example.pdfstyle _sm = null;
b4j.example.pdfstack _stack = null;
 //BA.debugLineNum = 88;BA.debugLine="Sub margins";
 //BA.debugLineNum = 89;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 90;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 92;BA.debugLine="Dim hdr As PDFStyle = maker.CreateStyle(\"header\")";
_hdr = _maker._createstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 93;BA.debugLine="hdr.fontSize = 18";
_hdr._fontsize /*int*/  = (int) (18);
 //BA.debugLineNum = 94;BA.debugLine="hdr.bold = True";
_hdr._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 95;BA.debugLine="hdr.alignmentRight = True";
_hdr._alignmentright /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 96;BA.debugLine="hdr.SetMargin(0, 190, 0, 80)";
_hdr._setmargin /*b4j.example.pdfstyle*/ ((int) (0),(int) (190),(int) (0),(int) (80));
 //BA.debugLineNum = 97;BA.debugLine="maker.AddStyle(hdr)";
_maker._addstyle /*String*/ (_hdr);
 //BA.debugLineNum = 99;BA.debugLine="Dim sh As PDFStyle = maker.CreateStyle(\"subheader";
_sh = _maker._createstyle /*b4j.example.pdfstyle*/ ("subheader");
 //BA.debugLineNum = 100;BA.debugLine="sh.fontSize = 14";
_sh._fontsize /*int*/  = (int) (14);
 //BA.debugLineNum = 101;BA.debugLine="maker.AddStyle(sh)";
_maker._addstyle /*String*/ (_sh);
 //BA.debugLineNum = 103;BA.debugLine="Dim sm As PDFStyle = maker.CreateStyle(\"superMarg";
_sm = _maker._createstyle /*b4j.example.pdfstyle*/ ("superMargin");
 //BA.debugLineNum = 104;BA.debugLine="sm.SetMargin(20, 0, 40, 0)";
_sm._setmargin /*b4j.example.pdfstyle*/ ((int) (20),(int) (0),(int) (40),(int) (0));
 //BA.debugLineNum = 105;BA.debugLine="sm.fontSize = 15";
_sm._fontsize /*int*/  = (int) (15);
 //BA.debugLineNum = 106;BA.debugLine="maker.AddStyle(sm)";
_maker._addstyle /*String*/ (_sm);
 //BA.debugLineNum = 108;BA.debugLine="Dim stack As PDFStack = maker.CreateStack";
_stack = _maker._createstack /*b4j.example.pdfstack*/ ();
 //BA.debugLineNum = 109;BA.debugLine="stack.AddString(\"This header has both top and bot";
_stack._addstring /*b4j.example.pdfstack*/ ("This header has both top and bottom margins defined");
 //BA.debugLineNum = 110;BA.debugLine="stack.AddText(maker.CreateText(\"This is a subhead";
_stack._addtext /*b4j.example.pdfstack*/ (_maker._createtext /*b4j.example.pdftext*/ ("This is a subheader")._setstyle /*b4j.example.pdftext*/ ("subheader"));
 //BA.debugLineNum = 111;BA.debugLine="stack.style.AddStyle(\"header\")";
_stack._style /*b4j.example.pdfstyle*/ ._addstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 113;BA.debugLine="maker.AddStack(stack)";
_maker._addstack /*b4j.example.pdfmaker*/ (_stack);
 //BA.debugLineNum = 115;BA.debugLine="maker.open";
_maker._open /*String*/ ();
 //BA.debugLineNum = 116;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Private fx As JFX";
_fx = new anywheresoftware.b4j.objects.JFX();
 //BA.debugLineNum = 4;BA.debugLine="End Sub";
return "";
}
public static String  _tables() throws Exception{
b4j.example.pdfmaker _maker = null;
b4j.example.pdfstyle _hdr = null;
b4j.example.pdfstyle _sh = null;
b4j.example.pdfstyle _tableexample = null;
b4j.example.pdfstyle _tableheader = null;
b4j.example.pdftable _tbl = null;
b4j.example.pdftable _tble = null;
b4j.example.pdfrow _row = null;
b4j.example.pdftable _tbld = null;
b4j.example.pdfrow _row1 = null;
 //BA.debugLineNum = 14;BA.debugLine="Sub tables";
 //BA.debugLineNum = 15;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 16;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 18;BA.debugLine="Dim hdr As PDFStyle = maker.CreateStyle(\"header\")";
_hdr = _maker._createstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 19;BA.debugLine="hdr.fontSize = 18";
_hdr._fontsize /*int*/  = (int) (18);
 //BA.debugLineNum = 20;BA.debugLine="hdr.bold = True";
_hdr._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 21;BA.debugLine="hdr.setmargin(0,0,0,10)";
_hdr._setmargin /*b4j.example.pdfstyle*/ ((int) (0),(int) (0),(int) (0),(int) (10));
 //BA.debugLineNum = 22;BA.debugLine="maker.AddStyle(hdr)";
_maker._addstyle /*String*/ (_hdr);
 //BA.debugLineNum = 25;BA.debugLine="Dim sh As PDFStyle = maker.CreateStyle(\"subheader";
_sh = _maker._createstyle /*b4j.example.pdfstyle*/ ("subheader");
 //BA.debugLineNum = 26;BA.debugLine="sh.fontSize = 16";
_sh._fontsize /*int*/  = (int) (16);
 //BA.debugLineNum = 27;BA.debugLine="sh.bold = True";
_sh._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 28;BA.debugLine="sh.SetMargin(0, 10, 0, 5)";
_sh._setmargin /*b4j.example.pdfstyle*/ ((int) (0),(int) (10),(int) (0),(int) (5));
 //BA.debugLineNum = 29;BA.debugLine="maker.AddStyle(sh)";
_maker._addstyle /*String*/ (_sh);
 //BA.debugLineNum = 31;BA.debugLine="Dim tableExample As PDFStyle = maker.CreateStyle(";
_tableexample = _maker._createstyle /*b4j.example.pdfstyle*/ ("tableExample");
 //BA.debugLineNum = 32;BA.debugLine="tableExample.SetMargin(0, 5, 0, 15)";
_tableexample._setmargin /*b4j.example.pdfstyle*/ ((int) (0),(int) (5),(int) (0),(int) (15));
 //BA.debugLineNum = 33;BA.debugLine="maker.AddStyle(tableExample)";
_maker._addstyle /*String*/ (_tableexample);
 //BA.debugLineNum = 35;BA.debugLine="Dim tableHeader As PDFStyle = maker.CreateStyle(\"";
_tableheader = _maker._createstyle /*b4j.example.pdfstyle*/ ("tableHeader");
 //BA.debugLineNum = 36;BA.debugLine="tableHeader.bold = True";
_tableheader._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 37;BA.debugLine="tableHeader.fontSize = 13";
_tableheader._fontsize /*int*/  = (int) (13);
 //BA.debugLineNum = 38;BA.debugLine="tableHeader.color = \"black\"";
_tableheader._color /*String*/  = "black";
 //BA.debugLineNum = 39;BA.debugLine="maker.AddStyle(tableHeader)";
_maker._addstyle /*String*/ (_tableheader);
 //BA.debugLineNum = 41;BA.debugLine="Dim tbl As PDFTable = maker.CreateTable";
_tbl = _maker._createtable /*b4j.example.pdftable*/ ();
 //BA.debugLineNum = 42;BA.debugLine="tbl.style.AddStyle(\"tableExample\")";
_tbl._style /*b4j.example.pdfstyle*/ ._addstyle /*b4j.example.pdfstyle*/ ("tableExample");
 //BA.debugLineNum = 43;BA.debugLine="tbl.AddColumn(\"Column 1\", Null, Null)";
_tbl._addcolumn /*b4j.example.pdftable*/ ("Column 1",anywheresoftware.b4a.keywords.Common.Null,anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 44;BA.debugLine="tbl.AddColumn(\"Column 2\", Null, Null)";
_tbl._addcolumn /*b4j.example.pdftable*/ ("Column 2",anywheresoftware.b4a.keywords.Common.Null,anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 45;BA.debugLine="tbl.AddColumn(\"Column 3\", Null, Null)";
_tbl._addcolumn /*b4j.example.pdftable*/ ("Column 3",anywheresoftware.b4a.keywords.Common.Null,anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 47;BA.debugLine="tbl.AddRow(Array(\"One value goes here\", \"Another";
_tbl._addrow /*b4j.example.pdftable*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("One value goes here"),(Object)("Another one here"),(Object)("OK?")}));
 //BA.debugLineNum = 48;BA.debugLine="maker.AddTable(tbl)";
_maker._addtable /*b4j.example.pdfmaker*/ (_tbl);
 //BA.debugLineNum = 50;BA.debugLine="Dim tblE As PDFTable = maker.CreateTable";
_tble = _maker._createtable /*b4j.example.pdftable*/ ();
 //BA.debugLineNum = 51;BA.debugLine="tblE.style.AddStyle(\"tableExample\")";
_tble._style /*b4j.example.pdfstyle*/ ._addstyle /*b4j.example.pdfstyle*/ ("tableExample");
 //BA.debugLineNum = 52;BA.debugLine="tblE.AddColumn(\"width=100\", 100, Null)";
_tble._addcolumn /*b4j.example.pdftable*/ ("width=100",(Object)(100),anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 53;BA.debugLine="tblE.AddColumn(\"star-sized\", \"*\", Null)";
_tble._addcolumn /*b4j.example.pdftable*/ ("star-sized",(Object)("*"),anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 54;BA.debugLine="tblE.AddColumn(\"width=200\", 200, Null)";
_tble._addcolumn /*b4j.example.pdftable*/ ("width=200",(Object)(200),anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 55;BA.debugLine="tblE.AddColumn(\"star-sized\", \"*\", Null)";
_tble._addcolumn /*b4j.example.pdftable*/ ("star-sized",(Object)("*"),anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 57;BA.debugLine="Dim row As PDFRow = maker.CreateRow";
_row = _maker._createrow /*b4j.example.pdfrow*/ ();
 //BA.debugLineNum = 58;BA.debugLine="row.AddString(\"fixed-width cells have exactly the";
_row._addstring /*b4j.example.pdfrow*/ ("fixed-width cells have exactly the specified width");
 //BA.debugLineNum = 59;BA.debugLine="row.AddText(maker.CreateText(\"nothing interesting";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("nothing interesting here")._setitalics /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setcolor /*b4j.example.pdftext*/ ("gray"));
 //BA.debugLineNum = 60;BA.debugLine="row.AddText(maker.CreateText(\"nothing interesting";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("nothing interesting here")._setitalics /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setcolor /*b4j.example.pdftext*/ ("gray"));
 //BA.debugLineNum = 61;BA.debugLine="row.AddText(maker.CreateText(\"nothing interesting";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("nothing interesting here")._setitalics /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setcolor /*b4j.example.pdftext*/ ("gray"));
 //BA.debugLineNum = 62;BA.debugLine="tblE.AddRow1(row)";
_tble._addrow1 /*b4j.example.pdftable*/ (_row);
 //BA.debugLineNum = 63;BA.debugLine="maker.AddTable(tblE)";
_maker._addtable /*b4j.example.pdfmaker*/ (_tble);
 //BA.debugLineNum = 66;BA.debugLine="Dim tblD As PDFTable = maker.CreateTable";
_tbld = _maker._createtable /*b4j.example.pdftable*/ ();
 //BA.debugLineNum = 67;BA.debugLine="tblD.style.color = \"#444\"";
_tbld._style /*b4j.example.pdfstyle*/ ._color /*String*/  = "#444";
 //BA.debugLineNum = 68;BA.debugLine="tblD.SetWidths(Array(200, \"auto\", \"auto\"))";
_tbld._setwidths /*b4j.example.pdftable*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)(200),(Object)("auto"),(Object)("auto")}));
 //BA.debugLineNum = 69;BA.debugLine="tblD.headerRows = 2";
_tbld._headerrows /*int*/  = (int) (2);
 //BA.debugLineNum = 71;BA.debugLine="Dim row As PDFRow = maker.CreateRow";
_row = _maker._createrow /*b4j.example.pdfrow*/ ();
 //BA.debugLineNum = 72;BA.debugLine="row.AddText(maker.CreateText(\"Header with Colspan";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header with Colspan = 2")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setcolspan /*b4j.example.pdftext*/ ((int) (2))._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 73;BA.debugLine="row.AddEmpty";
_row._addempty /*b4j.example.pdfrow*/ ();
 //BA.debugLineNum = 74;BA.debugLine="row.AddText(maker.CreateText(\"Header 3\").SetStyle";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header 3")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 75;BA.debugLine="tblD.AddRow1(row)";
_tbld._addrow1 /*b4j.example.pdftable*/ (_row);
 //BA.debugLineNum = 77;BA.debugLine="Dim row1 As PDFRow = maker.CreateRow";
_row1 = _maker._createrow /*b4j.example.pdfrow*/ ();
 //BA.debugLineNum = 78;BA.debugLine="row1.AddText(maker.CreateText(\"Header 1\").SetStyl";
_row1._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header 1")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 79;BA.debugLine="row1.AddText(maker.CreateText(\"Header 2\").SetStyl";
_row1._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header 2")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 80;BA.debugLine="row1.AddText(maker.CreateText(\"Header 3\").SetStyl";
_row1._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header 3")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 81;BA.debugLine="tblD.AddRow1(row1)";
_tbld._addrow1 /*b4j.example.pdftable*/ (_row1);
 //BA.debugLineNum = 84;BA.debugLine="maker.AddTable(tblD)";
_maker._addtable /*b4j.example.pdfmaker*/ (_tbld);
 //BA.debugLineNum = 85;BA.debugLine="maker.open";
_maker._open /*String*/ ();
 //BA.debugLineNum = 86;BA.debugLine="End Sub";
return "";
}
}
