package b4j.example;


import anywheresoftware.b4a.BA;

public class pgpdf extends Object{
public static pgpdf mostCurrent = new pgpdf();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.pgpdf", null);
		ba.loadHtSubs(pgpdf.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.pgpdf", ba);
		}
	}
    public static Class<?> getObject() {
		return pgpdf.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static anywheresoftware.b4j.objects.JFX _fx = null;
public static com.ab.banano.BANano _banano = null;
public static b4j.example.pdfmaker _maker = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static String  _basic() throws Exception{
 //BA.debugLineNum = 50;BA.debugLine="Sub basic";
 //BA.debugLineNum = 51;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 52;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 53;BA.debugLine="maker.AddString(\"First paragraph\")";
_maker._addstring /*b4j.example.pdfmaker*/ ("First paragraph");
 //BA.debugLineNum = 54;BA.debugLine="maker.AddString(\"Another paragraph, this time a l";
_maker._addstring /*b4j.example.pdfmaker*/ ("Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines");
 //BA.debugLineNum = 55;BA.debugLine="maker.Download(\"basic.pdf\")";
_maker._download /*String*/ ("basic.pdf");
 //BA.debugLineNum = 56;BA.debugLine="End Sub";
return "";
}
public static String  _columns() throws Exception{
b4j.example.pdfcolumns _cols = null;
b4j.example.pdfcolumns _cols3 = null;
b4j.example.pdfcolumns _cols4 = null;
b4j.example.pdfcolumns _cols5 = null;
b4j.example.pdfcolumns _cols6 = null;
b4j.example.pdftext _txt = null;
b4j.example.pdfcolumns _col7 = null;
b4j.example.pdfstyle _style1 = null;
b4j.example.pdfstyle _style2 = null;
b4j.example.pdfcolumns _colx = null;
 //BA.debugLineNum = 239;BA.debugLine="Sub columns";
 //BA.debugLineNum = 240;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 241;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 242;BA.debugLine="maker.defaultStyle.columnGap = 20";
_maker._defaultstyle /*b4j.example.pdfstyle*/ ._columngap /*int*/  = (int) (20);
 //BA.debugLineNum = 244;BA.debugLine="maker.AddString(\"Here we have 2 equal sized colum";
_maker._addstring /*b4j.example.pdfmaker*/ ("Here we have 2 equal sized columns...");
 //BA.debugLineNum = 246;BA.debugLine="Dim cols As PDFColumns = maker.CreateColumns";
_cols = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 247;BA.debugLine="cols.style.alignmentjustify = True";
_cols._style /*b4j.example.pdfstyle*/ ._alignmentjustify /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 248;BA.debugLine="cols.AddText(maker.CreateText(\"Column 1\"))";
_cols._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 1"));
 //BA.debugLineNum = 249;BA.debugLine="cols.AddText(maker.CreateText(\"Column 2\"))";
_cols._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2"));
 //BA.debugLineNum = 250;BA.debugLine="maker.AddColumns(cols)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols);
 //BA.debugLineNum = 253;BA.debugLine="maker.AddString(\"Here we have 3 equal sized colum";
_maker._addstring /*b4j.example.pdfmaker*/ ("Here we have 3 equal sized columns...");
 //BA.debugLineNum = 254;BA.debugLine="Dim cols3 As PDFColumns = maker.CreateColumns";
_cols3 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 255;BA.debugLine="cols3.AddText(maker.CreateText(\"Column 1\"))";
_cols3._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 1"));
 //BA.debugLineNum = 256;BA.debugLine="cols3.AddText(maker.CreateText(\"Column 2\"))";
_cols3._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2"));
 //BA.debugLineNum = 257;BA.debugLine="cols3.AddText(maker.CreateText(\"Column 3\"))";
_cols3._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 3"));
 //BA.debugLineNum = 258;BA.debugLine="maker.AddColumns(cols3)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols3);
 //BA.debugLineNum = 261;BA.debugLine="maker.AddString(\"Here we specify widths for each";
_maker._addstring /*b4j.example.pdfmaker*/ ("Here we specify widths for each column...");
 //BA.debugLineNum = 262;BA.debugLine="Dim cols4 As PDFColumns = maker.CreateColumns";
_cols4 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 263;BA.debugLine="cols4.AddText(maker.CreateText(\"Column 1\").SetWid";
_cols4._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 1")._setwidth /*b4j.example.pdftext*/ (BA.NumberToString(90)));
 //BA.debugLineNum = 264;BA.debugLine="cols4.AddText(maker.CreateText(\"Column 2\").SetWid";
_cols4._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 265;BA.debugLine="cols4.AddText(maker.CreateText(\"Column 3\").SetWid";
_cols4._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 3")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 266;BA.debugLine="cols4.AddText(maker.CreateText(\"Column 4\").SetWid";
_cols4._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 4")._setwidth /*b4j.example.pdftext*/ (BA.NumberToString(90)));
 //BA.debugLineNum = 267;BA.debugLine="maker.AddColumns(cols4)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols4);
 //BA.debugLineNum = 269;BA.debugLine="maker.AddString(\"Auto columns set their width dep";
_maker._addstring /*b4j.example.pdfmaker*/ ("Auto columns set their width depending on their content...");
 //BA.debugLineNum = 270;BA.debugLine="Dim cols5 As PDFColumns = maker.CreateColumns";
_cols5 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 271;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 1\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 1")._setwidth /*b4j.example.pdftext*/ ("auto"));
 //BA.debugLineNum = 272;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 2\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 273;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 3\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 3")._setwidth /*b4j.example.pdftext*/ (BA.NumberToString(50)));
 //BA.debugLineNum = 274;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 4\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 4")._setwidth /*b4j.example.pdftext*/ ("auto"));
 //BA.debugLineNum = 275;BA.debugLine="cols5.AddText(maker.CreateText(\"Column 5\").SetWid";
_cols5._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 5")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 276;BA.debugLine="maker.AddColumns(cols5)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols5);
 //BA.debugLineNum = 278;BA.debugLine="maker.AddString(\"Nesting columns...\")";
_maker._addstring /*b4j.example.pdfmaker*/ ("Nesting columns...");
 //BA.debugLineNum = 279;BA.debugLine="Dim cols6 As PDFColumns = maker.CreateColumns";
_cols6 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 280;BA.debugLine="Dim txt As PDFText = maker.CreateText(\"This is my";
_txt = _maker._createtext /*b4j.example.pdftext*/ ("This is my text for nested columns...");
 //BA.debugLineNum = 281;BA.debugLine="txt.style.fontSize = 9";
_txt._style /*b4j.example.pdfstyle*/ ._fontsize /*int*/  = (int) (9);
 //BA.debugLineNum = 282;BA.debugLine="txt.style.width = 100";
_txt._style /*b4j.example.pdfstyle*/ ._width /*String*/  = BA.NumberToString(100);
 //BA.debugLineNum = 283;BA.debugLine="cols6.AddText(txt)";
_cols6._addtext /*b4j.example.pdfcolumns*/ (_txt);
 //BA.debugLineNum = 285;BA.debugLine="cols6.AddText(maker.CreateText(\"Column 2\").SetWid";
_cols6._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 2")._setwidth /*b4j.example.pdftext*/ ("auto"));
 //BA.debugLineNum = 286;BA.debugLine="cols6.AddText(maker.CreateText(\"Column 3\").SetWid";
_cols6._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Column 3")._setwidth /*b4j.example.pdftext*/ ("*"));
 //BA.debugLineNum = 288;BA.debugLine="Dim col7 As PDFColumns = maker.CreateColumns";
_col7 = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 289;BA.debugLine="col7.AddString(\"This is nested!\")";
_col7._addstring /*b4j.example.pdfcolumns*/ ("This is nested!");
 //BA.debugLineNum = 290;BA.debugLine="col7.AddString(\"This is another nested column!\")";
_col7._addstring /*b4j.example.pdfcolumns*/ ("This is another nested column!");
 //BA.debugLineNum = 292;BA.debugLine="cols6.AddColumns(col7)";
_cols6._addcolumns /*b4j.example.pdfcolumns*/ (_col7);
 //BA.debugLineNum = 293;BA.debugLine="maker.AddColumns(cols6)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_cols6);
 //BA.debugLineNum = 296;BA.debugLine="Dim style1 As PDFStyle = maker.CreateStyle(\"bigge";
_style1 = _maker._createstyle /*b4j.example.pdfstyle*/ ("bigger");
 //BA.debugLineNum = 297;BA.debugLine="style1.fontSize = 18";
_style1._fontsize /*int*/  = (int) (18);
 //BA.debugLineNum = 298;BA.debugLine="style1.bold = True";
_style1._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 299;BA.debugLine="maker.AddStyle(style1)";
_maker._addstyle /*String*/ (_style1);
 //BA.debugLineNum = 301;BA.debugLine="Dim style2 As PDFStyle = maker.CreateStyle(\"heade";
_style2 = _maker._createstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 302;BA.debugLine="style2.fontSize = 15";
_style2._fontsize /*int*/  = (int) (15);
 //BA.debugLineNum = 303;BA.debugLine="style2.italics = True";
_style2._italics /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 304;BA.debugLine="maker.AddStyle(style2)";
_maker._addstyle /*String*/ (_style2);
 //BA.debugLineNum = 306;BA.debugLine="Dim colX As PDFColumns = maker.CreateColumns";
_colx = _maker._createcolumns /*b4j.example.pdfcolumns*/ ();
 //BA.debugLineNum = 307;BA.debugLine="colX.style.AddStyle(\"bigger\")";
_colx._style /*b4j.example.pdfstyle*/ ._addstyle /*b4j.example.pdfstyle*/ ("bigger");
 //BA.debugLineNum = 308;BA.debugLine="colX.AddString(\"This is some column data that use";
_colx._addstring /*b4j.example.pdfcolumns*/ ("This is some column data that users the 'bigger' style!");
 //BA.debugLineNum = 309;BA.debugLine="colX.AddText(maker.CreateText(\"Some text with 20";
_colx._addtext /*b4j.example.pdfcolumns*/ (_maker._createtext /*b4j.example.pdftext*/ ("Some text with 20 fontsize")._setfontsize /*b4j.example.pdftext*/ ((int) (20)));
 //BA.debugLineNum = 310;BA.debugLine="maker.AddColumns(colX)";
_maker._addcolumns /*b4j.example.pdfmaker*/ (_colx);
 //BA.debugLineNum = 312;BA.debugLine="maker.Download(\"columns.pdf\")";
_maker._download /*String*/ ("columns.pdf");
 //BA.debugLineNum = 313;BA.debugLine="End Sub";
return "";
}
public static String  _display() throws Exception{
 //BA.debugLineNum = 9;BA.debugLine="Sub display";
 //BA.debugLineNum = 10;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 11;BA.debugLine="maker.AddString(\"First paragraph\")";
_maker._addstring /*b4j.example.pdfmaker*/ ("First paragraph");
 //BA.debugLineNum = 12;BA.debugLine="maker.AddString(\"Another paragraph, this time a l";
_maker._addstring /*b4j.example.pdfmaker*/ ("Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines");
 //BA.debugLineNum = 14;BA.debugLine="maker.Upload(Me, \"doUpload\", \"basic.pdf\")";
_maker._upload /*String*/ (pgpdf.getObject(),"doUpload","basic.pdf");
 //BA.debugLineNum = 15;BA.debugLine="End Sub";
return "";
}
public static String  _doupload(com.ab.banano.BANanoObject _fd) throws Exception{
anywheresoftware.b4a.objects.collections.Map _res = null;
String _status = "";
b4j.example.pdfview _view = null;
 //BA.debugLineNum = 17;BA.debugLine="Sub doUpload(fd As BANanoObject)";
 //BA.debugLineNum = 18;BA.debugLine="Dim res As Map = BANano.FromJson(BANano.CallAjaxW";
_res = new anywheresoftware.b4a.objects.collections.Map();
_res.setObject((anywheresoftware.b4a.objects.collections.Map.MyMap)(_banano.FromJson(_banano.CallAjaxWait("http://localhost/demo/assets/upload.php","POST","application/pdf",(Object)(_fd.getObject()),anywheresoftware.b4a.keywords.Common.False,(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null))))));
 //BA.debugLineNum = 19;BA.debugLine="Dim status As String = res.Get(\"status\")";
_status = BA.ObjectToString(_res.Get((Object)("status")));
 //BA.debugLineNum = 20;BA.debugLine="Select Case status";
switch (BA.switchObjectToInt(_status,"success","error")) {
case 0: {
 //BA.debugLineNum = 22;BA.debugLine="Dim view As PDFView";
_view = new b4j.example.pdfview();
 //BA.debugLineNum = 23;BA.debugLine="view.Initialize(\"basic\").SetHREF(\"./assets/basic";
_view._initialize /*b4j.example.pdfview*/ (ba,"basic")._sethref /*b4j.example.pdfview*/ ("./assets/basic.pdf")._setwidth /*b4j.example.pdfview*/ ("100%")._setheight /*b4j.example.pdfview*/ ("600")._refresh /*String*/ ();
 break; }
case 1: {
 break; }
}
;
 //BA.debugLineNum = 26;BA.debugLine="End Sub";
return "";
}
public static String  _images() throws Exception{
 //BA.debugLineNum = 28;BA.debugLine="Sub images";
 //BA.debugLineNum = 29;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 30;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 32;BA.debugLine="maker.Preload(\"one\", \"./assets/1.jpg\")";
_maker._preload /*b4j.example.pdfmaker*/ ("one","./assets/1.jpg");
 //BA.debugLineNum = 33;BA.debugLine="maker.Preload(\"seven9\", \"./assets/79.jpg\")";
_maker._preload /*b4j.example.pdfmaker*/ ("seven9","./assets/79.jpg");
 //BA.debugLineNum = 34;BA.debugLine="maker.Preload(\"yuna\", \"./assets/yuna.jpg\")";
_maker._preload /*b4j.example.pdfmaker*/ ("yuna","./assets/yuna.jpg");
 //BA.debugLineNum = 36;BA.debugLine="maker.AddString(\"Image Manipulation\")";
_maker._addstring /*b4j.example.pdfmaker*/ ("Image Manipulation");
 //BA.debugLineNum = 37;BA.debugLine="maker.AddImage(maker.CreateImage(\"one\").SetWidth(";
_maker._addimage /*b4j.example.pdfmaker*/ (_maker._createimage /*b4j.example.pdfimage*/ ("one")._setwidth /*b4j.example.pdfimage*/ ((int) (150))._setheight /*b4j.example.pdfimage*/ ((int) (150)));
 //BA.debugLineNum = 39;BA.debugLine="maker.AddString(\"You can also fit the image insid";
_maker._addstring /*b4j.example.pdfmaker*/ ("You can also fit the image inside a rectangle'");
 //BA.debugLineNum = 40;BA.debugLine="maker.AddImage(maker.CreateImage(\"yuna\").SetFit(1";
_maker._addimage /*b4j.example.pdfmaker*/ (_maker._createimage /*b4j.example.pdfimage*/ ("yuna")._setfit /*b4j.example.pdfimage*/ ((int) (100),(int) (100))._setpagebreakafter /*b4j.example.pdfimage*/ ());
 //BA.debugLineNum = 42;BA.debugLine="maker.AddString(\"and opacity is supported\")";
_maker._addstring /*b4j.example.pdfmaker*/ ("and opacity is supported");
 //BA.debugLineNum = 43;BA.debugLine="maker.AddImage(maker.CreateImage(\"seven9\").SetWid";
_maker._addimage /*b4j.example.pdfmaker*/ (_maker._createimage /*b4j.example.pdfimage*/ ("seven9")._setwidth /*b4j.example.pdfimage*/ ((int) (150))._setopacity /*b4j.example.pdfimage*/ (0.5));
 //BA.debugLineNum = 45;BA.debugLine="maker.AddString(\"place image at xy\")";
_maker._addstring /*b4j.example.pdfmaker*/ ("place image at xy");
 //BA.debugLineNum = 46;BA.debugLine="maker.AddImage(maker.CreateImage(\"seven9\").SetWid";
_maker._addimage /*b4j.example.pdfmaker*/ (_maker._createimage /*b4j.example.pdfimage*/ ("seven9")._setwidth /*b4j.example.pdfimage*/ ((int) (60))._setheight /*b4j.example.pdfimage*/ ((int) (60))._setabsoluteposition /*b4j.example.pdfimage*/ ((int) (500),(int) (50)));
 //BA.debugLineNum = 47;BA.debugLine="maker.Download(\"images.pdf\")";
_maker._download /*String*/ ("images.pdf");
 //BA.debugLineNum = 48;BA.debugLine="End Sub";
return "";
}
public static String  _inlinestyles() throws Exception{
b4j.example.pdfstyle _s1 = null;
b4j.example.pdfstyle _s2 = null;
b4j.example.pdftext _hdr = null;
b4j.example.pdfparagraphs _para = null;
 //BA.debugLineNum = 209;BA.debugLine="Sub inlineStyles";
 //BA.debugLineNum = 210;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 211;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 213;BA.debugLine="Dim s1 As PDFStyle = maker.CreateStyle(\"header\")";
_s1 = _maker._createstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 214;BA.debugLine="s1.fontSize = 18";
_s1._fontsize /*int*/  = (int) (18);
 //BA.debugLineNum = 215;BA.debugLine="s1.bold = True";
_s1._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 216;BA.debugLine="maker.AddStyle(s1)";
_maker._addstyle /*String*/ (_s1);
 //BA.debugLineNum = 218;BA.debugLine="Dim s2 As PDFStyle = maker.CreateStyle(\"bigger\")";
_s2 = _maker._createstyle /*b4j.example.pdfstyle*/ ("bigger");
 //BA.debugLineNum = 219;BA.debugLine="s2.fontsize = 15";
_s2._fontsize /*int*/  = (int) (15);
 //BA.debugLineNum = 220;BA.debugLine="s2.italics = True";
_s2._italics /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 221;BA.debugLine="maker.AddStyle(s2)";
_maker._addstyle /*String*/ (_s2);
 //BA.debugLineNum = 223;BA.debugLine="Dim hdr As PDFText = maker.CreateText(\"This is a";
_hdr = _maker._createtext /*b4j.example.pdftext*/ ("This is a header")._setstyle /*b4j.example.pdftext*/ ("header");
 //BA.debugLineNum = 224;BA.debugLine="maker.AddText(hdr)";
_maker._addtext /*String*/ (_hdr);
 //BA.debugLineNum = 226;BA.debugLine="Dim para As PDFParagraphs = maker.CreateParagraph";
_para = _maker._createparagraphs /*b4j.example.pdfparagraphs*/ ();
 //BA.debugLineNum = 227;BA.debugLine="para.AddString(\"It is however possible to provide";
_para._addstring /*b4j.example.pdfparagraphs*/ ("It is however possible to provide an array of texts ");
 //BA.debugLineNum = 228;BA.debugLine="para.AddString(\"to the paragraph (instead of a si";
_para._addstring /*b4j.example.pdfparagraphs*/ ("to the paragraph (instead of a single string) and have ");
 //BA.debugLineNum = 229;BA.debugLine="para.AddText(maker.CreateText(\"a better \").SetFon";
_para._addtext /*b4j.example.pdfparagraphs*/ (_maker._createtext /*b4j.example.pdftext*/ ("a better ")._setfontsize /*b4j.example.pdftext*/ ((int) (15))._setbold /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 230;BA.debugLine="para.AddString(\"control over it. \\nEach inline ca";
_para._addstring /*b4j.example.pdfparagraphs*/ ("control over it. \\nEach inline can be ");
 //BA.debugLineNum = 231;BA.debugLine="para.AddText(maker.CreateText(\"styled \").SetFontS";
_para._addtext /*b4j.example.pdfparagraphs*/ (_maker._createtext /*b4j.example.pdftext*/ ("styled ")._setfontsize /*b4j.example.pdftext*/ ((int) (20)));
 //BA.debugLineNum = 232;BA.debugLine="para.AddText(maker.CreateText(\"independently \").S";
_para._addtext /*b4j.example.pdfparagraphs*/ (_maker._createtext /*b4j.example.pdftext*/ ("independently ")._setitalics /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setfontsize /*b4j.example.pdftext*/ ((int) (40)));
 //BA.debugLineNum = 233;BA.debugLine="para.AddString(\"then.\\n\\n\")";
_para._addstring /*b4j.example.pdfparagraphs*/ ("then.\\n\\n");
 //BA.debugLineNum = 234;BA.debugLine="maker.AddParagraphs(para)";
_maker._addparagraphs /*b4j.example.pdfmaker*/ (_para);
 //BA.debugLineNum = 236;BA.debugLine="maker.Download(\"inlinestyles.pdf\")";
_maker._download /*String*/ ("inlinestyles.pdf");
 //BA.debugLineNum = 237;BA.debugLine="End Sub";
return "";
}
public static String  _margins() throws Exception{
b4j.example.pdfstyle _hdr = null;
b4j.example.pdfstyle _sh = null;
b4j.example.pdfstyle _sm = null;
b4j.example.pdfstack _stack = null;
 //BA.debugLineNum = 179;BA.debugLine="Sub margins";
 //BA.debugLineNum = 180;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 181;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 183;BA.debugLine="Dim hdr As PDFStyle = maker.CreateStyle(\"header\")";
_hdr = _maker._createstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 184;BA.debugLine="hdr.fontSize = 18";
_hdr._fontsize /*int*/  = (int) (18);
 //BA.debugLineNum = 185;BA.debugLine="hdr.bold = True";
_hdr._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 186;BA.debugLine="hdr.alignmentRight = True";
_hdr._alignmentright /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 187;BA.debugLine="hdr.SetMargin(0, 190, 0, 80)";
_hdr._setmargin /*b4j.example.pdfstyle*/ ((int) (0),(int) (190),(int) (0),(int) (80));
 //BA.debugLineNum = 188;BA.debugLine="maker.AddStyle(hdr)";
_maker._addstyle /*String*/ (_hdr);
 //BA.debugLineNum = 190;BA.debugLine="Dim sh As PDFStyle = maker.CreateStyle(\"subheader";
_sh = _maker._createstyle /*b4j.example.pdfstyle*/ ("subheader");
 //BA.debugLineNum = 191;BA.debugLine="sh.fontSize = 14";
_sh._fontsize /*int*/  = (int) (14);
 //BA.debugLineNum = 192;BA.debugLine="maker.AddStyle(sh)";
_maker._addstyle /*String*/ (_sh);
 //BA.debugLineNum = 194;BA.debugLine="Dim sm As PDFStyle = maker.CreateStyle(\"superMarg";
_sm = _maker._createstyle /*b4j.example.pdfstyle*/ ("superMargin");
 //BA.debugLineNum = 195;BA.debugLine="sm.SetMargin(20, 0, 40, 0)";
_sm._setmargin /*b4j.example.pdfstyle*/ ((int) (20),(int) (0),(int) (40),(int) (0));
 //BA.debugLineNum = 196;BA.debugLine="sm.fontSize = 15";
_sm._fontsize /*int*/  = (int) (15);
 //BA.debugLineNum = 197;BA.debugLine="maker.AddStyle(sm)";
_maker._addstyle /*String*/ (_sm);
 //BA.debugLineNum = 199;BA.debugLine="Dim stack As PDFStack = maker.CreateStack";
_stack = _maker._createstack /*b4j.example.pdfstack*/ ();
 //BA.debugLineNum = 200;BA.debugLine="stack.AddString(\"This header has both top and bot";
_stack._addstring /*b4j.example.pdfstack*/ ("This header has both top and bottom margins defined");
 //BA.debugLineNum = 201;BA.debugLine="stack.AddText(maker.CreateText(\"This is a subhead";
_stack._addtext /*b4j.example.pdfstack*/ (_maker._createtext /*b4j.example.pdftext*/ ("This is a subheader")._setstyle /*b4j.example.pdftext*/ ("subheader"));
 //BA.debugLineNum = 202;BA.debugLine="stack.style.AddStyle(\"header\")";
_stack._style /*b4j.example.pdfstyle*/ ._addstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 204;BA.debugLine="maker.AddStack(stack)";
_maker._addstack /*b4j.example.pdfmaker*/ (_stack);
 //BA.debugLineNum = 206;BA.debugLine="maker.Download(\"margins.pdf\")";
_maker._download /*String*/ ("margins.pdf");
 //BA.debugLineNum = 207;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 4;BA.debugLine="Private fx As JFX";
_fx = new anywheresoftware.b4j.objects.JFX();
 //BA.debugLineNum = 5;BA.debugLine="Private BANano As BANano";
_banano = new com.ab.banano.BANano();
 //BA.debugLineNum = 6;BA.debugLine="Private maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 7;BA.debugLine="End Sub";
return "";
}
public static String  _tables() throws Exception{
b4j.example.pdfstyle _hdr = null;
b4j.example.pdfstyle _sh = null;
b4j.example.pdfstyle _tableexample = null;
b4j.example.pdfstyle _tableheader = null;
b4j.example.pdftable _tbl = null;
b4j.example.pdftable _tble = null;
b4j.example.pdfrow _row = null;
b4j.example.pdftable _tbld = null;
b4j.example.pdfrow _row1 = null;
 //BA.debugLineNum = 105;BA.debugLine="Sub tables";
 //BA.debugLineNum = 106;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 107;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 109;BA.debugLine="Dim hdr As PDFStyle = maker.CreateStyle(\"header\")";
_hdr = _maker._createstyle /*b4j.example.pdfstyle*/ ("header");
 //BA.debugLineNum = 110;BA.debugLine="hdr.fontSize = 18";
_hdr._fontsize /*int*/  = (int) (18);
 //BA.debugLineNum = 111;BA.debugLine="hdr.bold = True";
_hdr._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 112;BA.debugLine="hdr.setmargin(0,0,0,10)";
_hdr._setmargin /*b4j.example.pdfstyle*/ ((int) (0),(int) (0),(int) (0),(int) (10));
 //BA.debugLineNum = 113;BA.debugLine="maker.AddStyle(hdr)";
_maker._addstyle /*String*/ (_hdr);
 //BA.debugLineNum = 116;BA.debugLine="Dim sh As PDFStyle = maker.CreateStyle(\"subheader";
_sh = _maker._createstyle /*b4j.example.pdfstyle*/ ("subheader");
 //BA.debugLineNum = 117;BA.debugLine="sh.fontSize = 16";
_sh._fontsize /*int*/  = (int) (16);
 //BA.debugLineNum = 118;BA.debugLine="sh.bold = True";
_sh._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 119;BA.debugLine="sh.SetMargin(0, 10, 0, 5)";
_sh._setmargin /*b4j.example.pdfstyle*/ ((int) (0),(int) (10),(int) (0),(int) (5));
 //BA.debugLineNum = 120;BA.debugLine="maker.AddStyle(sh)";
_maker._addstyle /*String*/ (_sh);
 //BA.debugLineNum = 122;BA.debugLine="Dim tableExample As PDFStyle = maker.CreateStyle(";
_tableexample = _maker._createstyle /*b4j.example.pdfstyle*/ ("tableExample");
 //BA.debugLineNum = 123;BA.debugLine="tableExample.SetMargin(0, 5, 0, 15)";
_tableexample._setmargin /*b4j.example.pdfstyle*/ ((int) (0),(int) (5),(int) (0),(int) (15));
 //BA.debugLineNum = 124;BA.debugLine="maker.AddStyle(tableExample)";
_maker._addstyle /*String*/ (_tableexample);
 //BA.debugLineNum = 126;BA.debugLine="Dim tableHeader As PDFStyle = maker.CreateStyle(\"";
_tableheader = _maker._createstyle /*b4j.example.pdfstyle*/ ("tableHeader");
 //BA.debugLineNum = 127;BA.debugLine="tableHeader.bold = True";
_tableheader._bold /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 128;BA.debugLine="tableHeader.fontSize = 13";
_tableheader._fontsize /*int*/  = (int) (13);
 //BA.debugLineNum = 129;BA.debugLine="tableHeader.color = \"black\"";
_tableheader._color /*String*/  = "black";
 //BA.debugLineNum = 130;BA.debugLine="maker.AddStyle(tableHeader)";
_maker._addstyle /*String*/ (_tableheader);
 //BA.debugLineNum = 132;BA.debugLine="Dim tbl As PDFTable = maker.CreateTable";
_tbl = _maker._createtable /*b4j.example.pdftable*/ ();
 //BA.debugLineNum = 133;BA.debugLine="tbl.style.AddStyle(\"tableExample\")";
_tbl._style /*b4j.example.pdfstyle*/ ._addstyle /*b4j.example.pdfstyle*/ ("tableExample");
 //BA.debugLineNum = 134;BA.debugLine="tbl.AddColumn(\"Column 1\", Null, Null)";
_tbl._addcolumn /*b4j.example.pdftable*/ ("Column 1",anywheresoftware.b4a.keywords.Common.Null,anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 135;BA.debugLine="tbl.AddColumn(\"Column 2\", Null, Null)";
_tbl._addcolumn /*b4j.example.pdftable*/ ("Column 2",anywheresoftware.b4a.keywords.Common.Null,anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 136;BA.debugLine="tbl.AddColumn(\"Column 3\", Null, Null)";
_tbl._addcolumn /*b4j.example.pdftable*/ ("Column 3",anywheresoftware.b4a.keywords.Common.Null,anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 138;BA.debugLine="tbl.AddRow(Array(\"One value goes here\", \"Another";
_tbl._addrow /*b4j.example.pdftable*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("One value goes here"),(Object)("Another one here"),(Object)("OK?")}));
 //BA.debugLineNum = 139;BA.debugLine="maker.AddTable(tbl)";
_maker._addtable /*b4j.example.pdfmaker*/ (_tbl);
 //BA.debugLineNum = 141;BA.debugLine="Dim tblE As PDFTable = maker.CreateTable";
_tble = _maker._createtable /*b4j.example.pdftable*/ ();
 //BA.debugLineNum = 142;BA.debugLine="tblE.style.AddStyle(\"tableExample\")";
_tble._style /*b4j.example.pdfstyle*/ ._addstyle /*b4j.example.pdfstyle*/ ("tableExample");
 //BA.debugLineNum = 143;BA.debugLine="tblE.AddColumn(\"width=100\", 100, Null)";
_tble._addcolumn /*b4j.example.pdftable*/ ("width=100",(Object)(100),anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 144;BA.debugLine="tblE.AddColumn(\"star-sized\", \"*\", Null)";
_tble._addcolumn /*b4j.example.pdftable*/ ("star-sized",(Object)("*"),anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 145;BA.debugLine="tblE.AddColumn(\"width=200\", 200, Null)";
_tble._addcolumn /*b4j.example.pdftable*/ ("width=200",(Object)(200),anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 146;BA.debugLine="tblE.AddColumn(\"star-sized\", \"*\", Null)";
_tble._addcolumn /*b4j.example.pdftable*/ ("star-sized",(Object)("*"),anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 148;BA.debugLine="Dim row As PDFRow = maker.CreateRow";
_row = _maker._createrow /*b4j.example.pdfrow*/ ();
 //BA.debugLineNum = 149;BA.debugLine="row.AddString(\"fixed-width cells have exactly the";
_row._addstring /*b4j.example.pdfrow*/ ("fixed-width cells have exactly the specified width");
 //BA.debugLineNum = 150;BA.debugLine="row.AddText(maker.CreateText(\"nothing interesting";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("nothing interesting here")._setitalics /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setcolor /*b4j.example.pdftext*/ ("gray"));
 //BA.debugLineNum = 151;BA.debugLine="row.AddText(maker.CreateText(\"nothing interesting";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("nothing interesting here")._setitalics /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setcolor /*b4j.example.pdftext*/ ("gray"));
 //BA.debugLineNum = 152;BA.debugLine="row.AddText(maker.CreateText(\"nothing interesting";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("nothing interesting here")._setitalics /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setcolor /*b4j.example.pdftext*/ ("gray"));
 //BA.debugLineNum = 153;BA.debugLine="tblE.AddRow1(row)";
_tble._addrow1 /*b4j.example.pdftable*/ (_row);
 //BA.debugLineNum = 154;BA.debugLine="maker.AddTable(tblE)";
_maker._addtable /*b4j.example.pdfmaker*/ (_tble);
 //BA.debugLineNum = 157;BA.debugLine="Dim tblD As PDFTable = maker.CreateTable";
_tbld = _maker._createtable /*b4j.example.pdftable*/ ();
 //BA.debugLineNum = 158;BA.debugLine="tblD.style.color = \"#444\"";
_tbld._style /*b4j.example.pdfstyle*/ ._color /*String*/  = "#444";
 //BA.debugLineNum = 159;BA.debugLine="tblD.SetWidths(Array(200, \"auto\", \"auto\"))";
_tbld._setwidths /*b4j.example.pdftable*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)(200),(Object)("auto"),(Object)("auto")}));
 //BA.debugLineNum = 160;BA.debugLine="tblD.headerRows = 2";
_tbld._headerrows /*int*/  = (int) (2);
 //BA.debugLineNum = 162;BA.debugLine="Dim row As PDFRow = maker.CreateRow";
_row = _maker._createrow /*b4j.example.pdfrow*/ ();
 //BA.debugLineNum = 163;BA.debugLine="row.AddText(maker.CreateText(\"Header with Colspan";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header with Colspan = 2")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setcolspan /*b4j.example.pdftext*/ ((int) (2))._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 164;BA.debugLine="row.AddEmpty";
_row._addempty /*b4j.example.pdfrow*/ ();
 //BA.debugLineNum = 165;BA.debugLine="row.AddText(maker.CreateText(\"Header 3\").SetStyle";
_row._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header 3")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 166;BA.debugLine="tblD.AddRow1(row)";
_tbld._addrow1 /*b4j.example.pdftable*/ (_row);
 //BA.debugLineNum = 168;BA.debugLine="Dim row1 As PDFRow = maker.CreateRow";
_row1 = _maker._createrow /*b4j.example.pdfrow*/ ();
 //BA.debugLineNum = 169;BA.debugLine="row1.AddText(maker.CreateText(\"Header 1\").SetStyl";
_row1._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header 1")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 170;BA.debugLine="row1.AddText(maker.CreateText(\"Header 2\").SetStyl";
_row1._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header 2")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 171;BA.debugLine="row1.AddText(maker.CreateText(\"Header 3\").SetStyl";
_row1._addtext /*b4j.example.pdfrow*/ (_maker._createtext /*b4j.example.pdftext*/ ("Header 3")._setstyle /*b4j.example.pdftext*/ ("tableHeader")._setalignmentcenter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 172;BA.debugLine="tblD.AddRow1(row1)";
_tbld._addrow1 /*b4j.example.pdftable*/ (_row1);
 //BA.debugLineNum = 175;BA.debugLine="maker.AddTable(tblD)";
_maker._addtable /*b4j.example.pdfmaker*/ (_tbld);
 //BA.debugLineNum = 176;BA.debugLine="maker.Download(\"tables.pdf\")";
_maker._download /*String*/ ("tables.pdf");
 //BA.debugLineNum = 177;BA.debugLine="End Sub";
return "";
}
public static String  _toc() throws Exception{
b4j.example.pdfstyle _header = null;
b4j.example.pdfstyle _subheader = null;
b4j.example.pdfstyle _quotex = null;
b4j.example.pdfstyle _small = null;
b4j.example.pdftoc _tc = null;
b4j.example.pdftext _p1 = null;
 //BA.debugLineNum = 58;BA.debugLine="Sub toc";
 //BA.debugLineNum = 59;BA.debugLine="Dim maker As PDFMaker";
_maker = new b4j.example.pdfmaker();
 //BA.debugLineNum = 60;BA.debugLine="maker.Initialize";
_maker._initialize /*b4j.example.pdfmaker*/ (ba);
 //BA.debugLineNum = 63;BA.debugLine="Dim header As PDFStyle = maker.CreateStyle(\"heade";
_header = _maker._createstyle /*b4j.example.pdfstyle*/ ("header")._setfontsize /*b4j.example.pdfstyle*/ ((int) (18))._setbold /*b4j.example.pdfstyle*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 64;BA.debugLine="maker.AddStyle(header)";
_maker._addstyle /*String*/ (_header);
 //BA.debugLineNum = 66;BA.debugLine="Dim subheader As PDFStyle = maker.CreateStyle(\"su";
_subheader = _maker._createstyle /*b4j.example.pdfstyle*/ ("subheader")._setfontsize /*b4j.example.pdfstyle*/ ((int) (15))._setbold /*b4j.example.pdfstyle*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 67;BA.debugLine="maker.AddStyle(subheader)";
_maker._addstyle /*String*/ (_subheader);
 //BA.debugLineNum = 69;BA.debugLine="Dim quotex As PDFStyle = maker.CreateStyle(\"quote";
_quotex = _maker._createstyle /*b4j.example.pdfstyle*/ ("quote")._setitalics /*b4j.example.pdfstyle*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 70;BA.debugLine="maker.AddStyle(quotex)";
_maker._addstyle /*String*/ (_quotex);
 //BA.debugLineNum = 72;BA.debugLine="Dim small As PDFStyle = maker.CreateStyle(\"small\"";
_small = _maker._createstyle /*b4j.example.pdfstyle*/ ("small")._setfontsize /*b4j.example.pdfstyle*/ ((int) (8));
 //BA.debugLineNum = 73;BA.debugLine="maker.AddStyle(small)";
_maker._addstyle /*String*/ (_small);
 //BA.debugLineNum = 76;BA.debugLine="maker.AddText(maker.CreateText(\"This is a TOC exa";
_maker._addtext /*String*/ (_maker._createtext /*b4j.example.pdftext*/ ("This is a TOC example. Text elements marked with tocItem: true will be located in the toc. See below.")._setpagebreakafter /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 78;BA.debugLine="Dim tc As PDFToC = maker.CreateToc.SetTitle(maker";
_tc = _maker._createtoc /*b4j.example.pdftoc*/ ()._settitle /*b4j.example.pdftoc*/ (_maker._createtext /*b4j.example.pdftext*/ ("TABLE OF CONTENTS")._setstyle /*b4j.example.pdftext*/ ("header"));
 //BA.debugLineNum = 79;BA.debugLine="tc.SetNumberStyle(maker.CreateStyleOnly.SetBold(T";
_tc._setnumberstyle /*b4j.example.pdftoc*/ (_maker._createstyleonly /*b4j.example.pdfstyle*/ ()._setbold /*b4j.example.pdfstyle*/ (anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 80;BA.debugLine="maker.AddToc(tc)";
_maker._addtoc /*b4j.example.pdfmaker*/ (_tc);
 //BA.debugLineNum = 82;BA.debugLine="Dim p1 As PDFText = maker.CreateText(\"This is a h";
_p1 = _maker._createtext /*b4j.example.pdftext*/ ("This is a header, using header style")._setstyle /*b4j.example.pdftext*/ ("header");
 //BA.debugLineNum = 83;BA.debugLine="p1.SetTocItem(True)";
_p1._settocitem /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 84;BA.debugLine="p1.SetPageBreakBefore";
_p1._setpagebreakbefore /*b4j.example.pdftext*/ ();
 //BA.debugLineNum = 85;BA.debugLine="p1.SetTocStyle(maker.CreateStyleOnly.SetItalics(T";
_p1._settocstyle /*b4j.example.pdftext*/ (_maker._createstyleonly /*b4j.example.pdfstyle*/ ()._setitalics /*b4j.example.pdfstyle*/ (anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 86;BA.debugLine="p1.SetTocMargin(0, 10, 0, 0)";
_p1._settocmargin /*b4j.example.pdftext*/ ((int) (0),(int) (10),(int) (0),(int) (0));
 //BA.debugLineNum = 87;BA.debugLine="p1.SetTocNumberStyle(maker.CreateStyleOnly.SetIta";
_p1._settocnumberstyle /*b4j.example.pdftext*/ (_maker._createstyleonly /*b4j.example.pdfstyle*/ ()._setitalics /*b4j.example.pdfstyle*/ (anywheresoftware.b4a.keywords.Common.True)._setdecoration /*b4j.example.pdfstyle*/ ("underline"));
 //BA.debugLineNum = 88;BA.debugLine="maker.AddText(p1)";
_maker._addtext /*String*/ (_p1);
 //BA.debugLineNum = 90;BA.debugLine="maker.AddString(\"Lorem ipsum dolor sit amet, cons";
_maker._addstring /*b4j.example.pdfmaker*/ ("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam...");
 //BA.debugLineNum = 92;BA.debugLine="maker.AddText(maker.CreateText(\"Subheader 1 - usi";
_maker._addtext /*String*/ (_maker._createtext /*b4j.example.pdftext*/ ("Subheader 1 - using subheader style")._setstyle /*b4j.example.pdftext*/ ("subheader")._settocitem /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setpagebreakbefore /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 93;BA.debugLine="maker.AddString(\"Lorem ipsum dolor sit amet, cons";
_maker._addstring /*b4j.example.pdfmaker*/ ("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam...");
 //BA.debugLineNum = 94;BA.debugLine="maker.AddString(\"Lorem ipsum dolor sit amet, cons";
_maker._addstring /*b4j.example.pdfmaker*/ ("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam...");
 //BA.debugLineNum = 95;BA.debugLine="maker.AddString(\"Lorem ipsum dolor sit amet, cons";
_maker._addstring /*b4j.example.pdfmaker*/ ("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam...");
 //BA.debugLineNum = 97;BA.debugLine="maker.AddText(maker.CreateText(\"Subheader 2 - usi";
_maker._addtext /*String*/ (_maker._createtext /*b4j.example.pdftext*/ ("Subheader 2 - using subheader style")._setstyle /*b4j.example.pdftext*/ ("subheader")._settocitem /*b4j.example.pdftext*/ (anywheresoftware.b4a.keywords.Common.True)._setpagebreakbefore /*b4j.example.pdftext*/ ());
 //BA.debugLineNum = 98;BA.debugLine="maker.AddString(\"Lorem ipsum dolor sit amet, cons";
_maker._addstring /*b4j.example.pdfmaker*/ ("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam...");
 //BA.debugLineNum = 99;BA.debugLine="maker.AddString(\"Lorem ipsum dolor sit amet, cons";
_maker._addstring /*b4j.example.pdfmaker*/ ("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam...");
 //BA.debugLineNum = 101;BA.debugLine="maker.AddText(maker.CreateText(\"You can use multi";
_maker._addtext /*String*/ (_maker._createtext /*b4j.example.pdftext*/ ("You can use multiple styles")._setstyle /*b4j.example.pdftext*/ ("quote")._setstyle /*b4j.example.pdftext*/ ("small"));
 //BA.debugLineNum = 102;BA.debugLine="maker.Download(\"toc.pdf\")";
_maker._download /*String*/ ("toc.pdf");
 //BA.debugLineNum = 103;BA.debugLine="End Sub";
return "";
}
}
